### ISSUE TITLE
When will it be usable ?

### ISSUE THREAD

**Issue by Rohan-ult** [leshawn-rice/grabaphone#1]
I have some questions :

1.  When will it be usable ?
2.  Why API as service ?  You can just share the full database as JSON.
3.  Which website you scraped for data ?

**Comment by leshawn-rice** [comment]
> I have some questions :
> 
> 
> 
> 1.  When will it be usable ?
> 
> 2.  Why API as service ?  You can just share the hole database as JSON.
> 
> 3.  Which website you scraped for data ?

1. It should be up and usable in the next couple weeks

2. I don't fully understand the question. If you're asking why I don't just query the entire database and put the results in JSON on some page, it's to make sorting devices easier, and because this is a personal project for my portfolio.

3. I scraped the data from Phonearena.com

**Comment by Rohan-ult** [comment]
I need every device data... So Is this possible?

**Comment by leshawn-rice** [comment]
> I need every device data... So Is this possible? 

Yes. You will be able to send a request to get the first 100 devices. Then send another with an offset of 100 (it limits each request to returning 100 devices), until you have all 5000+ devices in the database.

**Comment by Rohan-ult** [comment]
Can I collaborate ? Help you to scrape the data?

**Comment by leshawn-rice** [comment]
> Can I collaborate ? Help you to scrape the data?
> 
> 

I appreciate the offer but all the methods for scraping the data have already been implemented. That said once v1 is finished if you would like to contribute, the project will remain open source so you're free to open up a PR!

**Comment by Rohan-ult** [comment]
Ok...Thanks!

**Comment by MaheshPeri19** [comment]
@leshawn-rice 

Hi,
It seems very good api to use. When can i expect this api for production ?

**Comment by leshawn-rice** [comment]
> @leshawn-rice 
> 
> 
> 
> Hi,
> 
> It seems very good api to use. When can we expect this api for production ?
> 
> 

It should be ready within a week or so. At this point I'm just finishing writing tests and polishing docs!

**Comment by MaheshPeri19** [comment]
Hi,

Any update on this ? Can we see it live ?
