### ISSUE TITLE
[New] Official TechSpecs API

### ISSUE THREAD

**Issue by realtechspecs** [leshawn-rice/grabaphone#2]
Hi everyone,

We're launching an API that provides an easy way for you to get the official technical specifications of any consumer electronics product in the world, just in a few seconds.

Our API is ready and currently in private beta.

Signup for early access here https://developer.techspecs.io/ and try our live product search engine at www.techspecs.io(powered by our API)

**Comment by leshawn-rice** [comment]
Issue opened to advertise someone elses API. Closed
